spring.application.name=gateway

server.port=${PORT}
eureka.client.serviceUrl.defaultZone=${URL}
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true